name: Model Training CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for data changes
        id: check-changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'training_data.csv'; then
            echo "CHANGED=true" >> $GITHUB_ENV
          else
            echo "CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Set up Python
        if: env.CHANGED == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        if: env.CHANGED == 'true'
        run: |
          pip install -r requirements.txt

      - name: Train model
        if: env.CHANGED == 'true'
        run: |
          python train_model.py
          echo "MODEL_FILE=linear_model.pkl" >> $GITHUB_ENV
          echo "COEFF_FILE=linear_model.txt" >> $GITHUB_ENV

      - name: Prepare release
        if: env.CHANGED == 'true'
        run: |
          # Configure git
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # Create release branch with only model files
          git checkout --orphan temp-release
          git rm -rf .
          git add ${{ env.MODEL_FILE }} ${{ env.CEFF_FILE }}
          git commit -m "Trained model $(date +'%Y-%m-%d')"
          
          # Force update release branch
          git branch -D release || true
          git branch -m release
          git push -f origin release

      - name: Create GitHub Release
        if: env.CHANGED == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: model-v${{ github.run_number }}
          name: "Model Release v${{ github.run_number }}"
          body: "Automated model release"
          draft: false
          prerelease: false
          files: |
            ${{ env.MODEL_FILE }}
            ${{ env.COEFF_FILE }}
